# Generated by Django 3.0.5 on 2020-05-02 22:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('online_grouper', '0002_auto_20200503_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Название')),
                ('description', models.CharField(max_length=300, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.AlterModelOptions(
            name='examination',
            options={'verbose_name': 'Обследование', 'verbose_name_plural': 'Обследования'},
        ),
        migrations.AlterModelOptions(
            name='measurement',
            options={'verbose_name': 'Измерение', 'verbose_name_plural': 'Измерения'},
        ),
        migrations.AlterField(
            model_name='examination',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='diagnosis',
            field=models.CharField(max_length=150, verbose_name='Диагноз'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='gender',
            field=models.CharField(max_length=20, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 2, 22, 50, 57, 701878, tzinfo=utc), verbose_name='Дата измерения'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='examination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='online_grouper.Examination', verbose_name='Обследование'),
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='signals/', verbose_name='Файл')),
                ('delta', models.FloatField(verbose_name='Дельта')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='online_grouper.Measurement', verbose_name='Измерение')),
            ],
            options={
                'verbose_name': 'Сигнал',
                'verbose_name_plural': 'Сигналы',
            },
        ),
        migrations.CreateModel(
            name='GroupExamination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_examinations', to='online_grouper.Examination', verbose_name='Обследование')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_examinations', to='online_grouper.Group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Обследование группы',
                'verbose_name_plural': 'Обследования группы',
            },
        ),
    ]
