# Generated by Django 3.0.5 on 2020-05-02 22:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('online_grouper', '0003_auto_20200503_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 2, 22, 52, 32, 36028, tzinfo=utc), verbose_name='Дата измерения'),
        ),
    ]
