# Generated by Django 3.0.5 on 2020-05-02 23:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('online_grouper', '0009_auto_20200503_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 2, 23, 51, 10, 318205, tzinfo=utc), verbose_name='Дата измерения'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='file',
            field=models.FileField(upload_to='signals/', verbose_name='Файл'),
        ),
    ]
