# Generated by Django 3.0.5 on 2020-05-03 01:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('online_grouper', '0011_auto_20200503_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 3, 1, 5, 24, 855347, tzinfo=utc), verbose_name='Дата измерения'),
        ),
    ]
