# Generated by Django 3.0.5 on 2020-05-03 12:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import online_grouper.validators


class Migration(migrations.Migration):

    dependencies = [
        ('online_grouper', '0012_auto_20200503_0405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupexamination',
            options={'verbose_name': 'Запись об обследованиях группы', 'verbose_name_plural': 'Записи об обследованиях группы'},
        ),
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 3, 12, 0, 22, 780496, tzinfo=utc), verbose_name='Дата измерения'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='file',
            field=models.FileField(upload_to='signals/', validators=[online_grouper.validators.validate_file_extension], verbose_name='Файл'),
        ),
    ]
