# Generated by Django 3.0.5 on 2020-05-03 14:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('online_grouper', '0013_auto_20200503_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 3, 14, 24, 20, 397936, tzinfo=utc), verbose_name='Дата измерения'),
        ),
    ]
